### ISSUE TITLE
[Bug] [WEB] Session超时不能自动跳转到登录页面 

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#1008]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dlink/issues?q=is%3Aissue) and found no similar issues.

### What happened

Session超时, 在页面上任何操作不生效, 或者直接报错

### What you expected to happen

session超时应该直接跳转到登录页面

### How to reproduce

等session超时, 目录下打开一个作业

### Version

dev

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jinyanhui2008** [comment]
我觉得这个是不是可以考虑把session模式改为cookie模式或者token模式

**Comment by wellCh4n** [comment]
This is a good feature, but, when we usually write flinksql, we may stay on this page for a long time, and when we save it, the session may expire.
这是一个很好的功能，但是，我们平时写flinksql的时候，可能会在这个页面停留很久，在保存的时候，可能session就过期了。

How to make sure our sql will not be lost because of page refresh? I think a simple way is to not jump to the login page in this page, and remind the user by a Modal to save it manually and then confirm the jump to the login page.
怎么保证我们的sql不会因为页面刷新丢失呢？我想到一个简单的方式是，在这个页面不跳转到登录页，通过一个Modal来提醒用户，让他手动保存后再确认跳转到登录页。

Do you have any suggestions?
您有什么建议吗？

**Comment by hdygxsj** [comment]
Can we make dinky support auto save in sql edit page

**Comment by gaoyan1998** [comment]
1.0 has added
