### ISSUE TITLE
[Optimization][Job Name] Job name support underline characters `-` to compatible with version 0.7

### ISSUE THREAD

**Issue by zhuxt2015** [DataLinkDC/dinky#3823]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar optimization requirement.

### Description

建议job名字支持下划线，这样能够兼容0.7版本的job名字。k8s中的pod名字可以替换job名字中的下划线为短横线
It is recommended that the job name be underline, so that it can be compatible with the 0.7 version of the job name. The pod name in k8s can be replaced underline with an dash in the job name.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment]
Good idea，Are you willing to be fix this issue？

**Comment by Zzm0809** [comment]
Can you contribute to this optimization?
If you plan to contribute to this optimization, because k8s tasks cannot support underscores, you need to add a tooltips to prompt the user when creating tasks. In all k8s modes, underscores will be replaced to avoid inconsistent task names resulting in a series of FAQs.
